// Generated by scripts/generate-viewer-tiles.py from bundled content assets.
// Do not hand-edit. One-pixel overlap extends each tile within the source bounds.
export type ArtworkTileSet = {
  width: number;
  height: number;
  tileSize: number;
  columns: number;
  rows: number;
  preview: string;
  basePath: string;
  extension: "webp" | "jpg";
  overlap: number;
};

export const artworkTileSets: Record<string, ArtworkTileSet> = {
  "/assets/content/viewer/death-of-socrates.jpg": {
    "width": 4000,
    "height": 2663,
    "tileSize": 512,
    "columns": 8,
    "rows": 6,
    "preview": "/assets/content/viewer/tiles/death-of-socrates/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/death-of-socrates",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/dante-portrait.jpg": {
    "width": 850,
    "height": 1296,
    "tileSize": 512,
    "columns": 2,
    "rows": 3,
    "preview": "/assets/content/viewer/tiles/divine-comedy/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/divine-comedy",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/chart-of-hell.jpg": {
    "width": 800,
    "height": 559,
    "tileSize": 512,
    "columns": 2,
    "rows": 2,
    "preview": "/assets/content/viewer/tiles/chart-of-hell/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/chart-of-hell",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/viewer/great-wave.jpg": {
    "width": 4096,
    "height": 2888,
    "tileSize": 512,
    "columns": 8,
    "rows": 6,
    "preview": "/assets/content/viewer/tiles/great-wave/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/great-wave",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/viewer/noh-mask.jpg": {
    "width": 1512,
    "height": 2000,
    "tileSize": 512,
    "columns": 3,
    "rows": 4,
    "preview": "/assets/content/viewer/tiles/noh-mask/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/noh-mask",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/viewer/arabic-bowl.jpg": {
    "width": 3791,
    "height": 3791,
    "tileSize": 512,
    "columns": 8,
    "rows": 8,
    "preview": "/assets/content/viewer/tiles/arabic-bowl/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/arabic-bowl",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/viewer/migrant-mother.jpg": {
    "width": 1661,
    "height": 2048,
    "tileSize": 512,
    "columns": 4,
    "rows": 4,
    "preview": "/assets/content/viewer/tiles/migrant-mother/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/migrant-mother",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/caligari-poster.jpg": {
    "width": 1206,
    "height": 1800,
    "tileSize": 512,
    "columns": 3,
    "rows": 4,
    "preview": "/assets/content/viewer/tiles/caligari/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/caligari",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/viewer/the-kiss.jpg": {
    "width": 3840,
    "height": 3853,
    "tileSize": 512,
    "columns": 8,
    "rows": 8,
    "preview": "/assets/content/viewer/tiles/the-kiss/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/the-kiss",
    "extension": "jpg",
    "overlap": 1
  },
  "/assets/content/viewer/girl-pearl.jpg": {
    "width": 3458,
    "height": 4096,
    "tileSize": 512,
    "columns": 7,
    "rows": 8,
    "preview": "/assets/content/viewer/tiles/girl-pearl/preview.jpg",
    "basePath": "/assets/content/viewer/tiles/girl-pearl",
    "extension": "jpg",
    "overlap": 1
  }
};
